# Changes here will be overwritten by Copier.
_commit: 1.8.5
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2021'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: false
project_description: Special Jinja2 extension for Copier that allows to load extensions
    using file paths relative to the template root instead of Python dotted paths.
project_name: Copier Templates Extensions
python_package_command_line_name: ''
python_package_distribution_name: copier-templates-extensions
python_package_import_name: copier_templates_extensions
repository_name: copier-templates-extensions
repository_namespace: copier-org
repository_provider: github.com

