blank_issues_enabled: false
contact_links:
- name: I have a question / I need help
  url: https://github.com/copier-org/copier-template-extensions/discussions/new?category=q-a
  about: Ask and answer questions in the Discussions tab.
