name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v1.1
      with:
        python-version: 3.8

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}

    - name: Check if the documentation builds correctly
      run: |
        pdm install -ds duty -s docs
        pdm run duty check-docs

    - name: Check the code quality
      run: |
        pdm install -ds duty -s quality --no-default
        pdm run duty check-code-quality

    - name: Check if the code is correctly typed
      run: |
        pdm install -ds duty -s typing --no-default
        pdm run duty check-types

    - name: Check for vulnerabilities in dependencies
      run: |
        pip install safety
        pdm install -ds duty --no-default
        pdm run duty check-dependencies

  tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v1.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pdm use -f ${{ matrix.python-version }}
        pdm install -ds duty -s tests

    - name: Run the test suite
      run: pdm run duty test
